# Generated by Django 5.1.3 on 2024-11-19 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTask', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='links', to='testTask.collection'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='unique_user_link'),
        ),
    ]
