# Generated by Django 5.1.3 on 2024-11-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testTask', '0002_alter_link_collections_alter_link_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
